# Generated by Django 5.0.3 on 2024-04-14 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MRIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(default='', max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prediction', models.FloatField(default=0)),
                ('mriScan', models.FileField(upload_to='mri_scans')),
            ],
        ),
    ]
