# Generated by Django 5.0.4 on 2024-04-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhd_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mriprediction',
            name='adhd_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
