# Generated by Django 5.0.4 on 2024-04-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhd_api', '0003_rename_adhd_type_mriprediction_adhdtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mriprediction',
            name='recommendations',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
