# Generated by Django 5.0.4 on 2024-04-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhd_api', '0004_mriprediction_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mriprediction',
            name='recommendations',
        ),
    ]
